description: <a href="https://github.com/rcowsill">github.com/rcowsill</a>
repository: rcowsill/rcowsill.github.io
remote_theme: pages-themes/slate@v0.2.0
kramdown:
  input: GFM
  gfm_quirks: [paragraph_end, no_auto_typographic]
