description: <a href="https://github.com/rcowsill">github.com/rcowsill</a>
repository: rcowsill/rcowsill.github.io
remote_theme: rcowsill/jekyll-theme-slate@v0.2.1-alpha
kramdown:
  input: GFM
  gfm_quirks: [paragraph_end, no_auto_typographic]
optional_front_matter:
  remove_originals: true
readme_index:
  remove_originals: true
defaults:
  - scope:
      path: "Electronics/TestCards"
    values:
      layout: "submodule"
      submodule_url: "https://github.com/rcowsill/TestCards"
  - scope:
      path: "Electronics/USCI40_demo"
    values:
      layout: "submodule"
      submodule_url: "https://github.com/rcowsill/USCI40_demo"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "**/LICENSE"
  - "**.asm"
  - "**.c"
  - "**.cmd"
